Repository 4cornerslatam/4Corners-client, pull requests merged in 2023-06, with the labels that each got.

#10 4 header UI implementation_first part
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/4cornersPink.svg
  src/assets/4cornersWhite.svg
  src/assets/logo_v1_rosa@2x.png
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/_header.scss
  src/components/Layout/Layout.tsx
  src/components/NavbarMobile/NavbarMobile.tsx
  src/components/NavbarOptionsList/NavbarOptionsList.tsx
  src/context/AppContext.tsx
  src/main.tsx
  src/styles/_componentName.scss
  src/styles/base/_reset.scss
  src/styles/base/_settings.scss
  src/styles/components/_footer.scss
  src/styles/components/_header.scss
  src/styles/components/_layout.scss
  src/styles/components/_navbarMovile.scss
  src/styles/components/_navbarOptionsList.scss
  src/styles/styles.scss
Labels: documentation, enhancement

#13 9 redaction json
  src/translation/spanish.json
Labels: documentation

#14 8-home-UI-implementation
  src/components/ButtonToServices/ButtonToServices.tsx
  src/pages/Home.tsx
  src/styles/base/_settings.scss
  src/styles/pages/_home.scss
  src/styles/styles.scss
Labels: enhancement, Styles

#20 Corrections 8 home UI implementation
  src/pages/Home.tsx
  src/styles/pages/_home.scss
Labels: help wanted

#22 11 footer UI implementation
  index.html
  public/vite.svg
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Layout/Layout.tsx
  src/components/NavbarMobile/NavbarMobile.tsx
  src/components/NavbarOptionsList/NavbarOptionsList.tsx
  src/pages/Contact.tsx
  src/pages/Services.tsx
  src/styles/components/_footer.scss
  src/styles/components/_navbarOptionsList.scss
Labels: enhancement, Styles

#25 12 a cerca de UI implementation
  package-lock.json
  package.json
  src/components/CarouselAbout/CarouselAbout.tsx
  src/pages/About.tsx
  src/styles/base/_settings.scss
  src/styles/components/_carouselAbout.scss
  src/styles/pages/_about.scss
  src/styles/styles.scss
  src/translation/spanish.json
Labels: documentation
